name: Count translation corruptions
'on':
  workflow_dispatch: null
  pull_request:
    paths:
    - src/languages/scripts/count-translation-corruptions.ts
    - src/languages/lib/correct-translation-content.js
    - .github/workflows/count-translation-corruptions.yml
    - .github/actions/node-npm-setup/action.yml
    - .github/actions/clone-translations/action.yml
    - package**.json
permissions:
  contents: read
jobs:
  count-translation-corruptions:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout English repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        token: ${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}
    - name: Clone all translations
      uses: ./.github/actions/clone-translations
      with:
        token: ${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}
    - uses: ./.github/actions/node-npm-setup
    - name: Run count
      run: npm run count-translation-corruptions
