name: Generate code scanning query lists
'on':
  workflow_dispatch:
    inputs:
      SOURCE_BRANCH:
        description: Branch to pull the source files from in the codeql repo (for
          example codeql-cli-2.x.x).
        type: string
        required: true
        default: main
  pull_request:
    paths:
    - .github/workflows/generate-code-scanning-query-lists.yml
    - src/code-scanning/scripts/generate-code-scanning-query-list.ts
    - .github/actions/install-cocofix/action.yml
permissions:
  contents: write
  pull-requests: write
jobs:
  generate-query-lists:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - uses: ./.github/actions/node-npm-setup
    - name: Checkout codeql repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        repository: github/codeql
        path: codeql
        ref: ${{ inputs.SOURCE_BRANCH || 'main' }}
    - name: Get the codeql SHA being synced
      id: codeql
      run: 'cd codeql

        OPENAPI_COMMIT_SHA=$(git rev-parse HEAD)

        echo "OPENAPI_COMMIT_SHA=$OPENAPI_COMMIT_SHA" >> $GITHUB_OUTPUT

        echo "Copied files from github/codeql repo. Commit SHA: $OPENAPI_COMMIT_SHA"

        '
    - name: Download CodeQL CLI
      uses: ./codeql/.github/actions/fetch-codeql
    - name: Test CodeQL CLI Download
      run: codeql --version
    - name: Start CodeQL CLI server in the background
      run: 'codeql execute cli-server &

        sleep 3

        codeql --version

        '
    - uses: ./.github/actions/install-cocofix
      with:
        token: ${{ secrets.DOCS_BOT_PAT_WORKFLOW }}
    - name: Lint the code (eslint)
      if: ${{ github.event_name == 'pull_request' }}
      env:
        PATH: $PATH:${{ github.workspace }}/node_modules/.bin
      run: 'eslint --no-ignore src/code-scanning/scripts/generate-code-scanning-query-list.ts

        '
    - name: Lint the code (tsc)
      if: ${{ github.event_name == 'pull_request' }}
      env:
        PATH: $PATH:${{ github.workspace }}/node_modules/.bin
      run: 'tsc --noEmit --project src/code-scanning/scripts/tsconfig.json

        '
    - name: Build code scanning query list
      run: "for lang in \"cpp\" \"csharp\" \"go\" \"java\" \"javascript\" \"python\"\
        \ \"ruby\" \"swift\"; do\n  echo \"Generating code scanning query list for\
        \ $lang\"\n  npm run generate-code-scanning-query-list -- \\\n    --verbose\
        \ \\\n    --codeql-path codeql \\\n    --codeql-dir codeql \\\n    -o data/reusables/code-scanning/codeql-query-tables/$lang.md\
        \ \\\n    $lang\ndone\n"
    - name: Insight into diff
      run: 'git diff

        '
    - name: Create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}
        DRY_RUN: ${{ github.event_name == 'pull_request'}}
      run: "\n# When we started, we downloaded the CodeQL CLI here in this workflow.\n\
        # We have no intention of checking that in but we also don't want\n# `git\
        \ status ...` to show it as an untracked file.\nrm -fr ./codeql\n\n# If nothing\
        \ to commit, exit now. It's fine. No orphans.\nchanges=$(git diff --name-only\
        \ | wc -l)\nuntracked=$(git status --untracked-files --short | wc -l)\nif\
        \ [[ $changes -eq 0 ]] && [[ $untracked -eq 0 ]]; then\n  echo \"There are\
        \ no changes to commit after running the generation and conversion scripts.\
        \ Exiting...\"\n  exit 0\nfi\n\ngit config --global user.name \"docs-bot\"\
        \ngit config --global user.email \"77750099+docs-bot@users.noreply.github.com\"\
        \n\nbranchname=codeql-query-tables-${{ steps.codeql.outputs.OPENAPI_COMMIT_SHA\
        \ }}\n\n# Exit if the branch already exists. Since the actions/checkout fetch-depth\
        \ is 1,\n# it doesn't \"know\" about branches locally, so we need to manually\
        \ list them.\nbranchExists=$(git ls-remote --heads origin refs/heads/$branchname\
        \ | wc -l)\n\n# When run on a pull_request, we're just testing the tooling.\n\
        # Exit before it actually pushes the possible changes.\nif [ \"$DRY_RUN\"\
        \ = \"true\" ]; then\n  echo \"Dry-run mode when run in a pull request\"\n\
        \  echo \"See the 'Insight into diff' step for the changes it would create\
        \ PR about.\"\n  exit 0\nfi\n\nif [ $branchExists -ne 0 ]; then\n  echo \"\
        Branch $branchname already exists in the remote repository.\"\n  exit 0\n\
        else\n  git checkout -b $branchname\nfi\n\ngit add data/reusables/code-scanning/codeql-query-tables\n\
        git commit -m \"Update CodeQL query tables\"\ngit push origin $branchname\n\
        \necho \"Creating pull request...\"\ngh pr create \\\n  --title \"Update CodeQL\
        \ query tables\" \\\n  --repo github/docs-internal \\\n --label \"codeql-query-tables,skip\
        \ FR board,ready-for-doc-review\" \\\n  --body '\U0001F44B humans. This PR\
        \ updates the **CodeQL query table reusables** with the latest changes in\
        \ preparation for the next **CodeQL CLI** release.\n\n  No action is required\
        \ from the first responder for the Docs content team. This PR will be reviewed\
        \ and merged by the Code scanning and GHAS focus team as part of the next\
        \ release of CodeQL CLI. (Synced from codeql@${{ steps.codeql.outputs.OPENAPI_COMMIT_SHA\
        \ }})\n\n  If CI does not pass or other problems arise, contact #docs-engineering\
        \ on slack.'\n"
