name: Sync OpenAPI schema
'on':
  workflow_dispatch:
    inputs:
      SOURCE_BRANCH:
        description: Branch to pull the dereferenced OpenAPI source files from in
          the github/rest-api-descriptions repo.
        type: string
        required: true
        default: main
  schedule:
  - cron: 20 16 * * *
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref
    || github.ref }}
  cancel-in-progress: true
jobs:
  generate-decorated-files:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Checkout rest-api-description repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        repository: github/rest-api-description
        path: rest-api-description
        ref: ${{ inputs.SOURCE_BRANCH }}
    - uses: ./.github/actions/node-npm-setup
    - name: Sync the REST, Webhooks, and GitHub Apps schemas
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_WRITEORG_PROJECT }}
      run: 'src/rest/scripts/update-files.js --source-repo rest-api-description --output
        rest github-apps webhooks rest-redirects

        git status

        echo "Deleting the cloned github/rest-api-description repo..."

        rm -rf rest-api-description

        '
    - name: Get the rest-api-description SHA being synced
      id: rest-api-description
      run: "OPENAPI_COMMIT_SHA=$(cat src/rest/lib/config.json | jq -r '.sha')\necho\
        \ \"OPENAPI_COMMIT_SHA=$OPENAPI_COMMIT_SHA\" >> $GITHUB_OUTPUT\necho \"Copied\
        \ files from github/rest-api-description repo. Commit SHA: $OPENAPI_COMMIT_SHA\"\
        \nif [ -z $OPENAPI_COMMIT_SHA ]; then\n  echo \"OpenAPI commit SHA is empty!\"\
        \n  exit 1\nfi\n"
    - name: Create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}
      run: "# If nothing to commit, exit now. It's fine. No orphans.\nchanges=$(git\
        \ diff --name-only | wc -l)\nif [[ $changes -eq 0 ]]; then\n  echo \"There\
        \ are no changes to commit after running src/rest/scripts/update-files.js.\
        \ Exiting...\"\n  exit 0\nfi\n\ngit config --global user.name \"docs-bot\"\
        \ngit config --global user.email \"77750099+docs-bot@users.noreply.github.com\"\
        \n\nbranchname=openapi-update-${{ steps.rest-api-description.outputs.OPENAPI_COMMIT_SHA\
        \ }}\n\nremotesha=$(git ls-remote --heads origin $branchname)\nif [ -n \"\
        $remotesha\" ]; then\n  # output is not empty, it means the remote branch\
        \ exists\n  echo \"Branch $branchname already exists in 'github/docs-internal'.\
        \ Exiting...\"\n  exit 0\nfi\n\ngit checkout -b $branchname\ngit add .\ngit\
        \ commit -m \"Add decorated OpenAPI schema files\"\ngit push origin $branchname\n\
        \necho \"Creating pull request...\"\ngh pr create \\\n  --title \"Update OpenAPI\
        \ Description\" \\\n  --body '\U0001F44B humans. This PR updates the OpenAPI\
        \ description with the latest changes. (Synced from github/rest-api-description@${{\
        \ steps.rest-api-description.outputs.OPENAPI_COMMIT_SHA }})\n\n  If CI does\
        \ not pass or other problems arise, contact #docs-engineering on slack.' \\\
        \n  --repo github/docs-internal \\\n  --label github-openapi-bot\n"
    - uses: ./.github/actions/slack-alert
      if: ${{ failure() && github.event_name != 'workflow_dispatch' }}
      with:
        slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
        slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
