name: Sync search - PR
'on':
  workflow_dispatch: null
  pull_request:
    paths:
    - src/search/**
    - package*.json
    - .github/workflows/sync-search-pr.yml
    - .github/actions/setup-elasticsearch/action.yml
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref
    || github.ref }}
  cancel-in-progress: true
env:
  ELASTICSEARCH_URL: http://localhost:9200
  HYDRO_ENDPOINT: ''
  HYDRO_SECRET: ''
jobs:
  dryRunElasticsearchIndexes:
    runs-on: ubuntu-latest
    if: github.repository == 'github/docs-internal'
    steps:
    - name: Check out repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Clone docs-internal-data
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        repository: github/docs-internal-data
        token: ${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}
        path: docs-internal-data
    - uses: ./.github/actions/setup-elasticsearch
    - uses: ./.github/actions/node-npm-setup
    - uses: ./.github/actions/cache-nextjs
    - name: Build
      run: npm run build
    - name: Start the server in the background
      env:
        ENABLE_DEV_LOGGING: false
      run: 'npm run sync-search-server > /tmp/stdout.log 2> /tmp/stderr.log &


        # first sleep to give it a chance to start

        sleep 6

        curl --retry-connrefused --retry 4 -I http://localhost:4002/

        '
    - if: ${{ failure() }}
      name: Debug server outputs on errors
      run: 'echo "____STDOUT____"

        cat /tmp/stdout.log

        echo "____STDERR____"

        cat /tmp/stderr.log

        '
    - name: Scrape records into a temp directory
      env:
        THROW_ON_EMPTY: false
        DOCS_INTERNAL_DATA: docs-internal-data
      run: "mkdir /tmp/records\nnpm run sync-search-indices -- /tmp/records \\\n \
        \ --language en \\\n  --version dotcom\n\nls -lh /tmp/records\n"
    - name: Check that Elasticsearch is accessible
      run: 'curl --fail --retry-connrefused --retry 5 -I ${{ env.ELASTICSEARCH_URL
        }}

        '
    - name: Index into Elasticsearch
      run: "npm run index-elasticsearch -- /tmp/records \\\n  --language en \\\n \
        \ --version dotcom\n"
    - name: Check created indexes and aliases
      run: 'curl --fail --retry-connrefused --retry 5 ${{ env.ELASTICSEARCH_URL }}/_cat/indices?v

        curl --fail --retry-connrefused --retry 5 ${{ env.ELASTICSEARCH_URL }}/_cat/indices?v

        '
